#+latex_class: book
#+title: Appellant's Desigtnation of Record on Appeal
#+author: Heyan "Jenny" Huang

* Statements
- 现在的问题是我需要把文件也传给表哥吗？可是我只有一两天的时间
－另外，法庭上还有哪些文件是需要我复制或是转达的吗
－我是否需要立即写封邮件问一下相关的工作人员

＊　个人的认知层面的问题　　
- 法律是有期限的：所有的限制令都有过期的期限
－ to be completed tomorrow

* 写给偶们亲爱的表哥的情书
  #+BEGIN_SRC text
亲爱的表哥，
我总是忍不住想要给亲爱的表哥写点儿什么
我总是忍不住想要写给亲爱的表哥的冲动
要怎么组织自己的小脑袋瓜里的思路才能够
在亲爱的表哥面前更好在表达自己呢？
  #+END_SRC 

- 下面是长周末，回家看表哥的时候写的
  #+BEGIN_SRC text
亲爱的表哥
这次回来
我终于找到了可是使用学校里帮助免费提供的无线网络
并且这次回来图书馆是开放的

不知道是不是前几天长途开车还没有缓过颈来
今天上午的脑袋还是昏昏的
还是说早上的咖啡里加得糖太多了犯昏呢？
于是乎，我再次坐进梦魅以求的图书馆里
做的事件是给亲爱的表哥写情书

每次回来
能够看见亲爱的表哥
我都总是狠开心
可是这次回来好几天了
我却还没能找到合适的机会看见亲爱的表哥

我知道舅舅和亲爱的表哥都是为我负责
所以才当年会早早地捶打911
无奈你的活宝妹早已是情根深种
心里面长了草种了草，心有所爱所庞
再来拔草
是舅舅和表哥用几十匹马、几十张火车皮来拉也拔不掉的

亲爱的表哥
10年底11年那时幼稚的自己
心心清清楚楚、明明白白地知道自己喜欢表哥
心里明白认定表哥
可是涉世不深，世俗里的障碍
让我固执地以为只要自己假装从来就不喜欢表哥
只要自己可以假装去爱上其它的人
只要自己能够按照世俗的标准
找个长相学历相配的人
便可以寐心地过完世俗标准下的一生

我以为我可以假装好一阵子
我以为我可以欺骗全世界
我以为我可以让所有的人都知道
我从来不曾爱过这样一位表哥
却原来我只假装得了一阵子
我以为我可以瞒天过海欺骗全世界
却原来我只是欺骗了我自己
浪费和虚度的从来都是自己的青春和光阴
我假装得了一时却假装不完一世

喜欢表哥
不是因为舅舅，不是因为任何感恩
情感中没有家庭轮理亲情关系上的感恩可言
更多也更应该是一个人内心情感的真正需求与向往
我喜欢表哥，不因为舅舅
喜欢表哥是因为，亲爱的表哥待我好
我曾被亲爱的表哥待我的好
真真切切、惊心动魂地感动过
感动到当时的自己就能清楚地认定
我遇见了对的人
这是我想要的幸福
我想要余生都被亲爱的表哥
温柔对待，时常宠爱，宠在心头掌心
亲爱的表哥，你看
你的这个妹妹从来都是把情感看得最重
把亲爱的表哥看得最重

曾经沧海难为水
除却巫山不是云
这两句话14个字成为我心口永远的痛
亲爱的表哥
我不止一次地问过你
你的心里是否留有别人的眼泪？
为什么你就一定接受不了你的这个活宝妹呢？
还是说，你只是简单地希望你的这个活宝妹
能够生活在大城市，能够物质上生活得相对好一点儿？

可是你的活宝妹从来都不是靠物质来活着的人呀
1997年当我第一次遇见舅舅的时候
2007年当我来到美国后再次找到舅舅的时候
真正能够捆绑和牵挂住人的从来都是情
是幼稚少女时代心有郁结时候的鼓励解脱
是心里有所向往便想要努力踏入这片向往的国度土地的愿望
你的妹妹从来不是靠物质活着的人
你的妹妹更多的是听从她自己内心的声音活着
可是亲爱的表哥
那场告别、那场遇见
亲爱的表哥与我能够走到一起，但是佳缘是天作之合
可是亲爱的表哥如果一再拒绝我，那你的妹妹我便成了在劫难逃
你的妹妹今生也无法逃过这场爱情的劫难
表哥，你一再拒绝，要你这个妹妹后半生怎么过？
终究还是只能导致这个妹妹后半生残破残缺不全的人生

我能够想到的两种原因，我个人更愿意去相信前者
人的情感难以理解却也最为强求不得
我无法强求亲爱的表哥寐心地娶我
但借由我自己的经历换位思考
希望亲爱的表哥即便如我所猜测般心有所属又求而不得
希望已经回到故乡、能够生活在亲人环绕中的表哥
在父母兄弟亲人的陪伴中能够渐渐放宽自己的标准
希望亲爱的表哥能够遇见自己喜欢的女孩子
或是亲爱的表哥能够与生活妥协、学会接纳你的活宝妹

问世间情为何物
只叫人生死相许
我的后半生最想要同亲爱的表哥生活在一起
可是生活的风浪不知道会将我（们）打向何方
即便亲爱的表哥一时半会儿近年月或是近一两年还不能接纳我
我也希望在不久的将来
亲爱的表哥能够遇见自己的幸福或是能够接纳我
任何时候，能够看见亲爱的表哥生活得幸福
都是我这辈子最快乐的事
虽然我自己想要的幸福，是与亲爱的表哥在一起

亲爱的表哥
这次走后，我还会经常回来
访寻亲爱的表哥、我们的足迹曾经遍历过的地方
哪天亲爱的表哥改变主意了
肯求亲爱的表哥一定第一时间告诉我
这辈子能够嫁给亲爱的表哥
对我来说，任何时候都不晚

自己寻找来到美国
能够遇见亲爱的表哥
对我来说，即便是情感里的在劫难逃
却也是生命的礼遇，我狠感激
要不然，生活就是一串口枯井，了无生趣
等我老了，若是还没能嫁给表哥
我就回来亲爱的表哥所在这个城镇
在亲爱的表哥家的对面或是不远处
买个小房子
每天能够看见亲爱的表哥从我的窗前经过
都会成为我每天最大的点缀与快乐
谢谢亲爱的表哥！今生能够遇见亲爱的表哥
是我最幸福快乐和感激的事
且行且珍惜
愿我们很快能够执子之手，携手到老！
  #+END_SRC 

* LOVE MY DEAR COUSIN: looking for PROFESSIONAL help form attorneys in related fields
Hi, 

I am facing *two different charges from Whitman
County Pullman WA*. 

The charges are: 
- 9A.36.041.2: ASSAULT 4TH DEGREE
- 9A.52.080: CRIMINAL TRESPASS-2ND DEGREE

I don't have any history with ASSAULT charges, and all the histories
of TRESPASS related were expired on 3/21/2017. 

I will be meeting the court judge soon within 2 - 3 weeks, and I am
looking for prefessional help to assist me though out the court dates and possibly
later trial. 

Please write to me *blue_water_000@hotmail.com*, if you are interested
and elligible for attorneys in *Whitman county, WA*, and please provide with your
quote as well. 

thanks. I look forward to hearing from you. 

