#+latex_class: book
#+title: deepwaterooo deepwateroooMe -- I am the same GitHub account person
#+author: deepwaterooo

* me
- My *deepwaterooo* GitHub account ownership was taken away from me temporatorily,
  without reasonable update when they are supposed to return my
  ownership. 
- This *deepwateroooMe* GitHub account is the temporatorily newly
  created one to maintain my security, watching deepwaterooo account. 
- Once *deepwaterooo* ownership is returned back to me, I will switch
  back to deepwaterooo, and *leave this one linked with deepwaterooo account.*
- My *emacs configuration is still messy right now*. Because *they hide almost all the 5 repositories to be private* that I have even commited into GitHub
  ever since I worked for the company, leaving me no way to sync up my
  emacs configurations, nor any other about 3 repositories. 

* LOVE MY DEAR COUSIN: looking for help form professional attorneys
Hi, 

I am facing two different charges from Whitman
County Pullman WA. 

The charges are: 
- 9A.36.041.2: ASSAULT 4TH DEGREE
- 9A.52.080: CRIMINAL TRESPASS-2ND DEGREE

I don't have any history with ASSAULT charges, and all the histories
of TRESPASS-2ND were expired on 3/21/2017. 

I will be meeting the court judge soon within 2 - 3 weeks, and I am looking for some
prefessional help to assist me though out the court dates and possible
alter trial. 

Please write to me *blue_water_000@hotmail.com*, if you are elligible
for attorneys in *Whitman county, WA*, and please provide with your
quote as well. 

thanks. I look forward to hearing from you. 

* LUCID MOTORS
- They claimed that they have noticed that there are lucid data
  leaking for the past 2-3 weeks.
- They monitor my working laptop 365 -7 - 24, and they pretended that
  they just noticed such a matter. 
- Quite a few files in my GitHub account a few repositories clearly indicated it was me already.
- Leaking data into my personal cell phone was inspired and required
  by group leand Tianshi Li that I should take videos whenever I do
  car testing. He did provided a phone initially, but then he took the
  phone away, how supposed I to record videos without a phone?
- They took GitHub account ownership away, took everything DIGITAL away from me. 
- When they took my GitHub deepwaterooo account ownership away, they
  promised that they will return to me on Saturday, and latest by
  Monday 5pm. 
- Now it is Tuesday evening already, but they are taking forever to return my ownship. I NEED MY
 GitHub deepwaterooo OWNERSHIP BACK!
- Meanwhile the landloard wifi company is trying every means to block
  me from uploading anything into my newly opened deepwateroooMe
  GitHub account. I am NOT able to upload any larger repositories any
  more except simple files.  

