#+latex_class: cn-article
#+title: Wired Behaviors
#+author: deepwaterooo

* 先前的：精于试探拿捏别人，一天试探拿捏别人100 遍
- 推荐信：【帮点儿小忙，一定索要回报】她是写了，但她把别人看成个 loser, 把给别人的推荐信一定写成距离别人千里之外。如此，仍能强势索要回报，要别人开车去接她回家。后来我有四封推荐信，也把有四封推荐信的提交过了申请的网页给她看过，她的这一封也不是必须的，因为别人会有多余的。
- 为试探擦边界，想开别人的车，把别人丢市中心走回去
  - 然后她第一时间问【先把你放进不得不走回去的恶劣环境，再试探比较容易成功？】：想开别人的车。回来她自己也说，两三个月之内，她自己也被丢市中心过，她也是自己走回去的。【真难相信，若是她自己也真走过，短时间不到三个月之内，她不会记得？还会把别人推荐上车，让别人也再走一回？】她报复开心地说，那天我终于成了 poor baby。我严重回复了她的试探：不可能。我不可能把没有她保险的车给一个【可能没有驾照】没有任何美国驾驶经验的人开。她太作梦了，她请另谋出路【买二手车，租车，随便她】。别打我的主意。
* 故意不理人，永远是前家门的最后一步，不得不回，最后一秒回复别人的消息，任何消息
- 可见这个人的内心得有多见不得人，多敏感才会如何极端的保护她自己【而实际上，这个人从来不清白】，却把别人恶心羞辱得要死，把别人，很多次帮助过她的人，在她那里，从来都只是她羞辱凌迟的对象，她还真高贵。。。。。太犯贱了。拿捏别人拿捏得过了分。
- 她一次写不完作业，是【提前十分钟，在她，还算是比较好的一次了】回复别人的消息
- 别人的关心问候在她那里也从来是她的最大耻辱，她一定在进家门前最后一步回复【不得不回的时候，回最不重要的消息】。别人，永远，关心问候的消息，都是，她的最大耻辱。

- 故意凉人，既发消息给别人，还能故意羞辱别人一样地故意不理，不止一回，她认为别人傻，没有自尊，任由她作贱羞辱凌迟

* 恶意抹黑、毁灭一个人的名声：2014 年秋天；和现沦陷了的可怜人室友
- 我到前天晚上才终于想明白，她这个卑微的早已经沦陷了的可怜人，每天所干的事是，想千方设百计故意叨难你，以试图以她个人的叨钻难缠行为抹黑你，一个正常普通人意外拥有的名声。
- 亲爱的表哥，她不是个人成名后历史上，第一个如此对待你活宝妹的，2014 年秋季学期，作为一个个人，被先前的学校和系里，也如此类似不公正对待过。只是因为方式不同，现室友伪装得深，离开校园后，狠久没有这样的室友，没有经验，没能及时反应过来。
- 但，个人生活中，她是伪装得最无古，城府最深，属马狮子座，最为强势，也最扭曲了别人的人格尊严，她的身份地位最为卑微，是个早已沦陷了的可怜人，靠身体发文章，发文章的数量（她对我自称，她国际上发表了28 篇文章）受身体检验。但她强势心狠手段毒辣。心机女的手段总是狠多，她既分身，极有可能只在家里作这样一个叨钻难缠，她既要别人生活中帮助她，她可以用车购物，她还要极不人道地故意一再作贱别人的尊严。叨钻女的本性暴露无遗。
** 简短陈述 2014 年秋天的情况
- 对于个人的什么时候成名，如何出名：作为同任何大众一样的卑微个人，我并没有很清楚的认识，那时的自己也狠年轻不经世事，不明白为什么会出名，以及不曾期待意外到来的名，会给自己带来什么。
- 2014 年秋天，先前的小学校UI 应该更多的是认为：一个国际留学生，却出奇【我自己也不知道是为什么？】地有比较大的名声，系里是有位某个专业方向上的大牛的，或许系里是认为作学教育系统的某个专业方向的牵头人，系里或觉得，若能及早灭掉一个普通国际留学生由于任何原因，所拥有的名气，或许是当时他们所认为的更为正确的做法？
- 于是2014 年秋天，作为一个最为普通，甚至是发展还点儿迟缓滞后的国际留学生，仍存在文化差异，认知问题等，便狠狠体验了一回，在出国留学的异国他乡，被系里专业课上一个小集体，搞孤立和差异对待的不幸记忆。
*** 系里专业上导师对自己抹黑灭名的方式是 *【项目专业能力上的指鹿为马，强加抹黑】* ：
- 秋天某次 LED Tower Light show （是秋天的9 月或是 10 月）, 是在校园中心用学生宿舍楼和窗子，每个里放LED 灯大型演示。那天下午，导师一定要求使用我有 Linux 系统的电脑来演示，这个项目里的任何同学都没有我所使用的那个 Linux-mint 系统版本？于是导师借一定要用我的笔记本电脑，将我捆绑在那天晚上的演示现场。但演示 demonstrate 的过程中，导师故意中途演示表演失败，这样，导师或系里便成功让，整座校园的师生认为【甚至有着求扩散传播的动机目的？】：这个国际留学生，专业能力不足，她项目【实则只是人被导师变向绑在现场】大型演示中途熄火，这让我作为一个国际留学生的专业能力，在整座校园【甚至接下来的整个求职生涯，可能延伸扩及的面，已经被所受教育的这个校园，掐死了一半】被强加一个巨大的问号。但实际上那个演示展示项目，是导师其它学生的项目，从来不是属于我的项目，与我没有半点儿关系。演示失败是导师故意的。除了导师一定要用我的电脑把我捆绑到演示现场，将这个演示中途失败的结果表象，强加强按在这个国际留学生的头上，那个项目与我半点儿关系也没有。但作为一个国际留学生的专业能力，却在整座校园，被人为强加一个？问号。自己后来的找工作等，也因为学校的恶意阻拦，招告天下的态度而遭受诸多挫折。 *国际留学生，来到这里读书，说到底，就是希望毕业了能够至少是顺利地找到份工作，好好生活发展，谁曾想望，在一所鸟不拉X 的小地方，读个书，拿个学位，临毕业了，还要被学校系里，把个人的发展给堵死、整死一半？任何人任何国际留学生都不会希望这种情况发生在他自己身上，但事实是，它就是可能会发生在任何国际留学生个人身上。*
*** 人际沟通合作能力上的打压：
- 那个秋天 *系里课程《Senior Design》上：呈现出两种可能的结果打法* ：一个小组的项目, 大概有四到五个成员。 
- *一种打法是：如果分配给我的组里的项目任务，我没能做出来，那么就打成是专业问题，专业成长能力不足【潜台词：不适给予提供工作机会；求扩散，打压这个人的发展】* ； 
- *另一种打法：如果我做出来了* ，那就是由代课老师指挥，由那个本科生女组长负责协调，将这个合作项目通过组长协调组员的一再擦边界，把别人的合作项目， *通过小组长一再与组员的协调与擦边界，打歪打成了人际沟通问题，这个人这个学生，沟通能力不足，不能够与他人合作【潜台词：不能与人很好沟通的人，发展应该受到限制】* 。
- 总结就是， *无论你在这个项目里的专业能力，人际沟通能力如何表现，他们都一定鸡蛋里挑骨头的做法，就是一定要纠出你的错来【不允许你发展，逼你读博士】* 。最后是因为自己的项目安时完成得很好，这个与本科生一起做的小组项目就，被打成了人际上的不能与人沟通，被代课老师要求，从合作项目里独立出去，我的项目被代课老师要求自己独立完成【另一个原因是， *项目也包括很多文书读写要求。国际学习受制于语言，语言文献上的读写能力，相比于计算机程序员的编程能力，可能会是他们更大的挑战，他们想要挑战你，以期待纠出你更多的不足* 】。
- *项目过程中，被项目小组搞围攻粗暴对待*： 
  - *无限放大一个小组成员缺点的做法是：被代课老师指导，小组长负责协调带动其它组员的，就是组里的每个成员都假装装作拥有你身上的一到二个缺点，当他们故意通过邮件或是某种方式将你身上也存在的这些缺点集中一一申明表明表现出来，故意制造焦点，故意制造社会关注点，那么所有其它组员共同执行代课老师的要求一起合作，就把你国际留学生一个个人身上十个八个缺点都一一放大出来，求焦点求关注，求社会工业界合力共同阻碍这个人的发展，逼国际留学生读博等，* 为的当然是阻止这个人的发展。
*** 系里对他们如些粗暴对待国际留学生，有自知之明吗？有，但打擦边球，为他们自己准备好借口
- 导师的借口是：我就是只是用了你的电脑，演示再球还有其它全部都是美国学生，因为项目里就是美国学生，只有你一个国际学生，难道我需要从哪里去拉个国际学生来给你作伴吗？
- Senior Design: 课的借口是：代课老师只有硕士学历，是院系里学历最低资历最低，专门负责系内各类脏活有损大牛们名誉的打扫卫生的活儿的。硕士教教本科生，资历相对欠缺，系里的态度就是：发生这种情况，谁也不愿意，但无可避免。他们只可以总结教训，不负责任何其它。 *国际留学生，面对别人故意打压限制你的手段，面对别人只总结教训不负责已经发生过的事的结果，你能强求说：我在这所学校这个系，遭受了这些不公平，你必段得给我补偿培偿一份工作吗？作梦吧，永远不可能。就是，发生在任何一个个人身上，就是任何个人个体的极大悲哀。这样的结果，是任何国际留学生不想，也不愿意看见的* 另一个他们的护身法是：把责任推泄给组员。他们是一群本科生不懂事的孩子，代课老师也不知道他们出于任何原因，合作团体对一个国际留学生构思执行实施了围攻粗暴对待。
- 没有读博：厌倦了那个环境，想逃跑。
** 再来看现室友：如2014 年秋天个人的遭遇是学校立场般，她，所代表的是WSU 的学校立场吗？不，她极端辱没了WSU 的校园文化。WSU 拥有上百年（125 年）的教育历史，公平透明，拥有极好的国际留学生学习环境
*** 作案手段手法：与2014 年秋天的遭遇院系集体，个人遭遇，如出一辄：有过之而不无及，隐藏深，手段狠，制造舆论焦点，恶意抹黑他人声誉
- 她是那个拿她自己土耳其国家的工资，也就是拿不到WSU 任何工资，出来合作一年，以免费劳动力服务于WSU 的某个项目。 *隐藏于她国际合作人公益人（因为她没有资格，拿WSU 的任何工资）身份，【想起来该是多么大公无私，勇于献身的精神】不容易被他人发现或是怀疑：*
- *只施加对一个人的恶意与暴力【只限于在家里，只对一个人，只对这个人施恶】* 。她在家里几种模式，可以想见，她在工作的地方，表现相对得体。在她工作项目上，她最卑微，比不上博士后拿美国导师的工资，比不上博士，有大好将来。 *她应该是不至于白天在实验室大象撞山把水龙头任何时候，哪怕半夜也开到最大，撞山响的*
- *用实验室公益人身份，和工作社交场合，所展现出来的正常，来维护她【成熟正常人形象】* ：足够成熟，社交礼仪得体。 *任何时候，似乎都不至于。对其它任何人，怎么样*. 
- *但实则在家里，在只有一个室友的地方：她分身* ，她如2014 年秋天项目里的同学般，无中生有【你没有错，故意制造强加给你各种错，甚至一度恶杀一个人正常的心智反应】；恶意寻三找四，故意制造各种事端， *不惜牺牲她个人在家里的形象，为的只是，抹黑你，一仍残存着一些在外名声的人。就是，以她一已之恶，之黑，来故意恶意抹黑别人* 但是因为她国际公益人身份，没有资格，拿不到WSU 一分钱工次，充当免费劳动力在这里一年，她在工作和社交场合的，【可以合理理解与想像】，正常的，得体的，绝不至于大象撞山的得体方式，保护维护他的正常人身份形象。
- 但她保护自己的方式是： *消息里对你各种冷落，把你当作是那个坏事做尽，不值得她这个室友回复消息或是尊重的天下最坏室友，各种冷漠，以予理采，甚至施加暴力【5-7 天故意躲她房间】* 。她把这种手段，当作是她的自卫，与对外宣称的他的立场：恶室友，不足以为伍，感觉羞耻。
- *故意制造焦点、炒作舆论：【5-7 天故意躲她房间】* 她，初到美国不足三个月，以一个国际异乡人的身份，发给了一场舆论风暴，想要恶意抹黑一个人的声名。实则，她才是那个有着诸多问题的可怜人。
*** 她，在个人住宿场所的个人行为，极端辱没WSU 校园文化。她是个案，是特例，无力无法，也不应该代表 WSU 校园官方立场
- 那么现室友，对一个同为国际人的室友，如此恶意行为，她代表的是哪方观点，或是意见？她能够代表传达的是WSU 对待一个稍微还残存点儿名声的先前国际留学生的立场吗？不，她的做法，极端辱灭了WSU 的校园文化。
- 她只是一个拿她自己土耳其国家的工资，出来做义工，积攒经验的，某个导师名下一个做义工，求机会学习这里先进项目经验的合作人。她甚至不是这里WSU 的博士后，因为她的工资由她自己找，是她自己的国家支付她，或者也可以简单地理解为，她自费，出来一年，在学习这里的先进经验的。
- 如果说，2014 年秋天，更多代表的是以前先前的小学校，作为拥有一个专业方向上一个大牛的系，一个教育机构，对一个微小个人的围攻，不人道行为。【这里我也申明一下自己作为个人的感受】
  - 【这里我也申明一下自己作为个人的感受】：我个人认为， *任何时候，一个系，一个群体，一座校园，对任何一个个人，哪怕是这个个人因为某种连她自己也不明白的原因意外拥有某种名声，对这个个人，施行不公正的群体围攻，都是不公正、不人道的行为。会给有着（哪怕是足够成熟，没有）文化差异的国际留学生的生活造成太大的困扰与不公，会影响其人对这个系，这个校园，或是这个国度的文化认知，或产生偏移错位* 。
  - 很多有点儿了解或是社会经验的国际留学生申请者， *哪怕是需要支付的学费相对稍微贵那么一点儿两点儿，也都会选择校园规模相对更大，更为公平公正、透明的学校院系，是有着足够道理的* 。
  - 好的学校，公平公正管理透明的学校，哪怕是自费必须交的学费稍微贵一点儿，但 *能够真正进入到一个好的体系体制受教育的学校，是一种半步一步已经迈进顺利成功【比如，最低生存标准：至少是毕业了能够在这边找份工作养家糊口吧？】的保障。* 而以个人亲身经历，比如个人临毕业前不幸经历“野鸡”大学的某种干扰，即便是毕业了拿到了学位，工作却受到教育系统的一定程度上的牵制，接下来的生存发展就必将受到更多的限制。 *说得再精准点儿，大家喜欢讲，赢在起跑线上，选择了规模小的“野鸡”大学，原本就是输在了起跑线上；而哪怕是刚出国时必须自费，选择了一所规模更大，更公平透明，拥有良好声誉的大学，哪怕是自费，能够想得开，其实已经是，就是赢在了起跑线上，哪怕刚出国时是自费出来，但这个管理完善、成熟的教育机制，已经能够保证保障其学生，毕业了找工作、工作发展能发展得好，就是胜利！这个时候，再来回看，刚出国时的那点儿学习费用，当然会珍惜和明白，有所投资有所回报。*
  - 因为普通国际留学生，亲爱的表哥，如你的活宝妹，从小长到大，品学兼优，考研究生考TOEFL, 考GRE 申请到奖学金出国留学，生活从来都顺利平静得不起任何波澜，作梦也不会想到，在一个异国他乡，任何可能会遭受到被孤立或是恶意对待的风险可能，但 *现实往往是，在一个竞争更为激烈的发达国家，这样的事情就是都有可能会发生、降落在任何普通大众国际留学生的身上，如你活宝妹的身上。而任何降临在一个卑微个人身上的这种被区别对待，都是一次头破血流、血淋淋的教训，又或者是生活的道路与选择，在这种无形中被扭曲扭转。*
  - 出国前，常年生活在菁菁校园的人，社会阅历一般极少。所受的教育，会让大家本能地相信：天是蓝的，水是清的，这个世界总是公平竞争的。。。。。顺利地拿到去往美国发达国家的鉴证，将来的路都必将是顺利的。。。。。但实际上，不夸张的说，确实有很多在国内表现优异的国际留学生初到异国他乡，并不真的知道或是明确接下来的生活目标是怎样的，甚至该如何在另一种文化中顺利顺滑圆润地生存。如果说在国内时努力学习的目标是为了出国，那真正出来后， *并不是每个人任何时候都能够明确坚定自己的学习目标，走错走偏时有发生* 。国内所受的教育受教育过程中极少可能出现被异端对待的情况，尤其对于从来都学习成绩好，三好学习，老师同学都喜欢的天之骄子来说。但 *出来后在一个竞争激烈的发达国家，会发现连校园、教育机构与体系都并不总是公平的，“野鸡”大学，或是规模较小的学校，不公正不透明，各种作法小家子气的所谓大学，如幺蛾子般的做法都极多，对国际留学生实行、执行必要的不公正对待、歧视甚至于恶意打压等现象，狠多，并非总如国内不了解情况下发想像理想的那样：天蓝水清，总能遇见最为美好的爱情，一切都是极好极好的。。。。。就连教育体系，也是存在诸多受教育不公正的* 。。。。。【过来人经历，个人现身说法】
  - 【 *很多时候，并不是任何一个真正遭遇这种对待的人，都有足够成熟的心智与坚强意志，面对这一切* 。哪些时时报道，想不开跳楼跳桥的，是为什么？】并不是任何一个顺风顺水成长成熟的人，都想当然地拥有面对突然变故，或处理生活中的意外的能力。
  - *大体上，就把出国留学生综合素质，分为两类，一类是各种综合素质好，就算人生第一次经受一场重大打击，都可以独立顺利处理过关* ；而 *有那另一类人，必得经历过他自己人生的第一次打击，方能成长心智真正成熟起来。这后一类人，若是所经受的第一场重大打击，是在远离亲人朋友的异国他乡，缺少这些至亲至爱的人的理解与支持，必将会是一场极大的考验* 。就算能够处理过关与不能过关各占50%, 面对那50% 失败的结果，这边博士、博士后跳楼跳桥的都很多，有学业中途废掉，比如被导师停助教助研经费，没有了奖学金学习生活成问题，回想起回国一跟学业上学习成绩独好【所谓聪明反被聪明误：除了成绩好，其它心智成问题。或是学习好便一直读，个人爱情婚姻生活成问题恋爱结婚严重滞后等】，无法接受现状结果，想不开轻生的。。。。。实在不要太多。 *没有发生在某个人体自己身上，自已就是开心顺利的一切；真正发生在某个个人个体身上，就成为一个个体个人的极大不幸与悲哀。*
  - 亲爱的表哥，活宝妹当年不是，多么明白的应该是继续读博，为什么逃离了那个地方？那些年的自己很年轻脆弱，长年生活在象牙塔校园里的活宝妹无力消化14 处秋天和接下来15 年春天所发生的一切。当时只有一个愿望，就是永远远离那个地方。但多年以后回望，当年的自己为什么没能读博呢？只是，再多十年的成长，让自己终于能够相对公平公正不带个人情感地去回忆当年已经发生过的事，对于当年自己遭受到的那些，近十年过去，现在的活宝妹终于可以原谅和释怀，可以平静地回忆。
- 她极端辱没了WSU 的校园文化。她所做的一切，更多的只是她个人一个卑微个人受困于成长或是心智素质，她自己个人心智性格或更多人品上的问题。她是她，她是存在于WSU 系统里的几乎最差存在。
- *她极端辱没了WSU 的校园文化* 。相反， *WSU拥有上百年（125 年）的教育历史，公平公正透明，拥有极好的国际留学生学习环境，支撑体系，不管是学业专业上校园教学楼，随处可见二维码扫描寻找同一专业上共同写作业的小伙伴们，还是生活问题上的支撑体系【对那些真正经历人生低谷的人来说，远离亲朋好友，真正困难的时候，当然是很强的支撑体系保障学生的心理精神需求】，校园文化以及管理体系，公平公正透明，以极佳的国际留学生培养成长体系环境闻名海内外。*
- WSU 拥有开放的校园文化。亲爱的表哥，活宝妹觉得自己狠卑微，是微不足道的尘埃。但作为最普通的平民老百姓，活宝妹仍能开怀开放地表达自已的观点认知与看法，去表达自己某方面的不公正被对待，而这里的 *公平公正开放的校园文化更为多元包容，永远都绝不至于会存在任何，对一个任何个人搞围攻施加暴力粗暴对待的可能，而更多的时候，是文化上的包容* 。是一座拥有极佳人文环境、人文关怀的国际留学生培养成长成才培育系统。从这座校园里走出去的学生，毕业生，综合素质都很好，找工作以及后来在社会上的发展也都很容易顺利成功。这样的校园文化，任何时候，绝不至于恶意对待一个国际留学生个人。国际留学生的申请者，申请的学校的基点基石，不正是严格需要这种保障保证吗？
- 亲爱的表哥，活宝妹有时候会怀疑自己：亲爱的表哥的，你的活宝妹真很奇葩吗？为什么你的活宝妹容易遇见如现室友这样的奇葩室友？心伤！！她，只是存在于WSU 的一个最小的意外。她这样的存在，应该只能反面刷新，这座有着开放人文文化人文校园，对她，是多么地包容善待。
- 亲爱的表哥，活宝妹有狠多话想要对亲爱的表哥表达。我先看看项目，下午或是傍晚，接下来再写完。
*** 她个人，与室友间所表现展现，她制造焦点，炒作了一场舆论背后成因分析 
**** 对她人的，情感婚姻信息，无力接收消化
     #+BEGIN_SRC text
亲爱的表哥
你的活宝妹观察注意到一个非常有趣的现象：

就是无论你活宝妹在室友面前
提过多少次，活宝妹是一定要嫁给亲爱的表哥的
活宝妹任何时候都是一定会嫁给亲爱的表哥的
活宝妹若是还没能嫁给亲爱的表哥
活宝妹就永远守候在亲爱的表哥的身边
在WSU 这座校园，这个小城生根发芽开花结果。。。。。

但是，哪怕是昨天我又再一次地她面前提起，
哪怕是明天，亲爱的表哥说，我们结婚吧
活宝妹都一定会开开心心地说，好，活宝妹这辈子的愿望终于达成！！！

但是，不知道现室友为什么34  岁还没有结婚
她说她希望明年她回去可以结婚，但她对活宝妹与亲爱的表哥的婚事反应
感觉她可能说的是假的，
因为无论别人千百次地在她面前提起说到，别人会希望能够尽快成婚

她的头脑，脑袋不知道哪根经搭错【还是她某方面生活经历的固执与执念】，
使得她，似乎永远接受不了，或是【别人重复了无数次的这个愿望信息】
似乎，永远无入真正进入她的意识内心
任何第一次初次了解到的人，都会印象深刻，知道这个室友是有男朋友
想要尽快结婚的状态
但是她关于别人的话与观点，反应出来的
就是别人的这条信息从来不曾真正进入她的意识
从来不曾被她的头脑真正主观接纳过接收到这条信息
是不是狠好玩儿？心理上，这是什么原因呢？

比如，在活宝妹千百次地提到会想要尽快成婚之后，
昨天再一次地说，秋天我可以申请WSU 的住宿后
活宝妹的内心突然想笑：为什么这一方面，她永远如此固执地把别人数百次传达的信息无法纳入她的印象？
活宝妹笑说：
如果活宝妹能够与亲爱的表哥及时成婚
自然是秋季不再需要申请WSU 的住宿的，活宝妹会同亲爱的表哥共同想办法解决住处问题；
如果活宝妹还没能与亲爱的表哥的及时成婚
活宝妹可能应该会去考虑：5 年读博，是否买一个相对便宜的 mobile home 之类的住处
在这座小镇扎根安家

活宝妹惊奇地观察到
原来从它人对一条信息，一类信息的反应
可以看出这个人对爱情，对情感，对婚姻的感受或是现状

不知道她，这个室友，
为什么就对别人有情感深厚的男友
别人会想要尽快成婚的信息，
永远无入真正纳入她的认知与意念
相对的，去感觉，她可能告诉我的，她的情感现状，与想明年回去后与她现男朋友结婚
也就未必是真实的
因为她反应出来的，对别人情感、婚姻的信息接纳状态呈现一个问号或是惊叹号？！！！
她为什么就固执地，永远接收不到别人有男朋友，会想要尽快成婚的这条这类信息？
你的活宝妹感觉这个方面，她的状态呈现得狠好玩儿。。。。。

爱表哥，爱生活！！！
活宝妹就是一定要嫁给亲爱的表哥
爱表哥，爱生活！！！
     #+END_SRC

**** 对某个方面的消息，极端过敏敏感，反应过敏，反应极端，缺乏对他人最基本的社会尊重，恶意炒作舆论
     #+BEGIN_SRC text
亲爱的表哥
你的活宝妹在与他人相处的过程中
也终于可以慢知慢觉地用自己的双眼，来观察和感觉
某些方面的异常：

比如昨天晚上感觉最明显的，
哪怕活宝妹在她面前提一万次，前半个小时还在说，活宝妹有男朋友，想要尽早嫁给亲爱的表哥
这条信息，关于活宝妹情感现状的这类信息

永远不被这个怪异的室友接收，她的头脑对于这类信息，
似乎在她，像是一阵儿风，左耳进右耳出，过后了无痕迹
她的头脑，从来不曾主观想起或是意识到，
这个室友曾无数次提过
有男朋友，会想要尽快结婚
她的头脑，反应出来任何时候，
她提到过的观点，意见建议，方方面面，
她把别人当成没有男朋友的单身孤立状态 

所以，活宝妹对于她这方面，情感方面的大脑信息处理能力持一个有趣儿的惊叹号怀疑态度
读得心理学方面的书极少，不知道这方面的专家如何分析解读这类现象

同样，相对的，如她前段时间所发起的一场风暴舆论般：
为什么她可以无数次撒谎敷衍你活宝妹
极没人品不地道地：既想用别人的车，还故意各种凉别人【把别人编造成离了她不成活一样】，与别人保持距离，似乎她与别人无任何联系，同了别人的车购物却以别人为极端无耻状态
她地道一点儿，实在一起，她心有嫌弃，她不可不必乘坐别人的车去买她要抽的烟，她自已乘座公交车去不就行了，何必故意伤害别人？
她既要用别人的车，她的故意凉别人，就是一种不地道
她接下来家里故意躲房间5-7 天与室友不见面不说话，如空气般不存在不用感知

那么，为什么这类信息方面，她初到美国三个月不到的国际人
又会如何地敏感过敏，作出种种过激极端反应？
可以远远走在舆论的最前面，甚至她自己以她极不地道的国际文化异乡人身份一手发起一场舆论？

说到底，说得重点儿，她自己要么就是早已沦陷了的可怜人【她对某类信息消息，有她根深蒂固的执念，某方面的脆弱，即是她沦陷了的原因，也是她今天对这类信息极端过敏的因果结果】
要么她的情感怪异，经历非同一般【可能想到的，比如说，是否，可能，她曾早在她自己的国家经受过人肉舆论暴力伤害，或是受到过极深的情感伤害？】所以呈现出某种过敏状态？
因为她是初到美国文化异乡人身份
其实大家也就当是看了个笑话，笑笑而已。没人真把她成某回事儿

只是，活宝妹总结，原来，人的头脑，处世，对不同类型信息的不同处理方式
能够反应呈现出一个人的头脑精神与认知现状
如果不用总结多的，她，可能就是一个有故事的人吧
每个人都很忙，谁真的去在意，她的故事又到是怎么的呢？
更多的是，呈现出，对一个有故意，或受到过伤害的，可怜的人，一种本能的人性上的善，尽量体谅与包容

爱表哥，爱生活！！！
活宝妹就是一定要嫁给亲爱的表哥
爱表哥，爱生活！！！
     #+END_SRC

*** 日常生活中表现出来的品性：随时随地撒谎
    #+BEGIN_SRC text
亲爱的表哥
她头脑狠灵，随时变换她表达的说话
也就成为了随时审时度势随机应变
另一种恶的情况就是，随时说谎，以最大限度地支撑她的立场

相信今天傍晚 aparment 的管理者
也亲自检测测试【比如外面站了五分钟，清楚地知道她在家抽烟了】她的撒谎应变情况
但是当管理者当她面问起，她就是立即当面撒谎否绝应变了
我相信这位管理者是，看破不说破，看她还要如此作恶下去吗？
观察过检测过，实在考查这个人的人品，相当于不说明不明说地警告过她了
她以后应该皮长紧点儿了

前天半夜两三点钟的最在水龙头
是昨天晚上十点我问起她
她先说先承认她是开到了最大（听她说想喝凉水的意思应该是喝的凉水cold 最大量，两大玻璃杯）
然后我提示说，以后晚上别人休息的时间她或许可以开小一点儿
但她随机应变，听我这建议后，她立即改口说她开得不是最大，她就是开的中小量什么的，假装是什么样的
那我见她又改口，当时就建议说，既然也不是每晚都夜间作息
或许夜间她作息别人休息之间，她可以用个容器把水先准备好。提前把水准备好
她再找借口说，她想喝凉水。。。但她自己也看了冰霜，我就没说话，她可以放冰霜里呀
然后今天再次说起，她又改口说，她想喝的是 fresh cold water from sink......
但她会小心一点儿
说到夜间两三点钟水龙头最大，她今天再绞辩一次说，她不是以为我两三点钟睡梦中醒来
她以为我两三点钟还不曾休息？！我从来至少11 点躺床上，即便偶尔因为她或没及时睡着或半夜醒来
别人是想醒着的状态；另则，她也该注意给邻居的不良影响
她就故意找借口说凌晨四五点邻居如何拍门
我说我从来没有听见过邻居恶意拍门
我说了：我们不能强求邻居怎么样，但是我们应该尽量去做好邻居 
她无语了

今天说到厨房水龙头开时，洗手间听起来会狠吵时
她也承认，她说她也早意识到傍晚我厨房洗餐具她在洗手间狠吵

活宝妹听到这话心里狠凉 
那么，活宝妹这里就有个问号：真巧，知道活宝妹跟她后面上厕所
她就刚好要喝水，还打了两大玻璃杯
她是真想喝水，还是她明知道别人半夜在用洗手间，真心更想故意吵别人？
她承认过的开的水量是cold 最大量，
那么她真正开过的是冷水的最大量，还是冷热水混合的最大量以便更吵最吵人？

今天是她在厨房放水我在洗手间测了一下
等改天她不在家，我会把冷水最大量，与冷热水混合的最大量再独自测试一遍
把她这条可能会以此夜间故意吵人的手段堵死
她以为若再这样，我自己在洗手间，可以随时测，随时录屏

爱表哥，爱生活！！！
活宝妹就是一定要嫁给亲爱的表哥
爱表哥，爱生活！！！    
#+END_SRC
* 帮助别人的人，最大的不幸悲哀，莫过于，你去帮助她，她把你当成她的耻辱，故意回避羞辱你，把你当作自贱狂，活该或是粘着她一样的跟屁虫？！！！
- 她，如果觉得不想要同别人一起，她大可不必跟别人一起去店里。
- 她，既要自己买东西，要跟别人去店里，想要用车，她又丝毫不去体会别人的感受，把别人的尊严辗压作贱至尽。
- 实则，她自己这个沦陷了的丑陋灵魂，没什么人品人格尊严可言。
- 她会心机地：进店前交待好，要你给她电话。她假惺惺发个消息，然后10 分钟，15 分钟之内，她都仍然可以故意假装，她没事儿人一样没听到你的消息，她故意不去看手机（逼你给她打电话，再把被逼成的给她打个电话当作别人的没有边界，催促了她？）【她的智商与高贵，让她不觉得别人应该可能会短时间内回复她的消息的，是她不值得被回复消息呢，还是她就是想要逼别人打电话给她？狠过分】，她就是故意不回复你，凉你！让你这个主动去帮助了她的人，感觉犯贱无耻，帮助她这样的人，实在是天下最大的耻辱！亲爱的表哥，她让你活宝妹感觉是你活宝妹发疯狂贱一定得帮她，粘着她，离了她不得活命。感觉极其恶心。
- 这之后，亲爱的表哥，活宝妹有心理阴影，极力不再去请她帮忙任何，极力不麻烦她，因为她善于索求回报，而帮助她却是你帮助她的人自己发疯狂贱无耻！！！

- 当一个人心里早预谋谋划了十万种故意抹黑你的方式：社交场合【短信消息里】，她对你的过分苛责与不理采，凉，与无足轻量，都会成为她变身作恶，分身作恶，只在你一个人身上作恶，故意各种恶意抹黑你十万次后，她恶事作尽了，在一个人面前恶人做完了，她却还要、还想要、还能够保全她自己的极端方式。所以，她从来就故意如此凉别人。
- 而这种故意抹黑他人的方式，也在个人历史中早发生过。最早是在2014 年秋季学期，同一个项目组里的组员恶意抹黑一个人，那时是那所破学校发动的，想要及早灭一个人的名吧。现在却是这个极端作恶的沦陷了的丑陋灵魂一个个人。

- 这之后，她凉了你活宝妹无数次，有一个周你活宝妹傍晚6:40pm 回家的时间，她每天傍晚这个时候一定是故意呆她房间里，一个周的时间里连续五到七天不见面不说话，形若空气不存在
- 他们炒作层，不得不关注XXX 的心理问题，实则是这个他们的托儿室友的故意孤立。她个沦陷了的可怜人，她的清白被大家全看在眼里，如果她还有任何清白可言的话。过敏过激故意糟蹋你活宝妹的人格尊严。为什么时时是她这样一个沦陷了的可怜人总是呆她房间，炒作层却总向她说话？因为她早沦陷了，她从来不清白。

- 她只是一个沦陷了的可怜人棋子，谁会有多想与她同住吗？谁不是高兴就多住两天，她羞辱了别人的尊严，作贱了别人，无中生有地无数次故意伤害了别人，别人当然随时搬走。而这一切，是她自已恶意作贱了别人的结果。有一种因果报应，叫活该。她自作孽不可活，她活该。她属马狮子一天到晚，强势拿捏作贱了别人，她只配活该她自己被孤立，不被当正常人看。她活该。

- 再后来一次忘记带钥匙，当然一定不想麻烦她，不麻烦她，才是可以保护自己的最大清白方式。因为有些人，麻烦不得麻烦不起。她当然拿捏作势，等到什么时候再回家，可是有谁又真的在意她如何呢？别人能够十一点进到家里，也从来不曾希望不曾对她有过任何希翼她会怎么样，她没有人品，没有 credit。因为她叨钻的本性早暴露得太多了，没人想再麻烦她任何。。。。。

- 活宝妹后来说是说了：她既然就是故意要把你活宝妹放在最不重要的位置，从今以后，她要帮助找她自己的朋友，别来烦我，活宝妹的时间狠宝贵，没时间每天被她折腾东折腾西的【以后就是这样，可以帮助这个世界上其它任何人，也绝不想，不情愿去帮她。】

- 知道征问过她关于 costco 的意见后，就是自己去的，不用带她，不用再自取其辱。

- 好心想到她说过喜欢吃某样东西，好心想到打扫卫生时她说不能扔空瓶，因为她等买 refill 了她还要用。
- 好心供她选，她自己作决定，结果好心全是驴肝肺，还甩锅别人。
- 还能无数次、数次三番无中生有，她想要要把别人折磨成失智吗？
- 那么又一次地被甩锅，又两次地被无中生有，
- 到现在终于清醒了吗？知道她是什么德性了吗？还有愿望与她有任保来往吗？什么也没有了

- 以后除了，不可避免之时，点头或与她说声 hi, 还会有胆量，还会有任何愿望想与她有任何交集吗？不想，太耻辱了。没有人还会再自取其辱。

- 会想要尽快搬走。愿从此不再与她有任何交集。
- 别人有个好的玻璃热水壶，她精明地一把收起了她自己的热水壶，两个人共用别人的好的，一两个月的时间不到就把别人的好热水壶，活宝妹自己休息前的最后一壶还烧得好好的，第二天早上起来就不能用了。
  - 她极端推泄责任，声称她什么也没有做。她没有表达任何负责任的做法或说法，甚至想逼别人不用她的热水壶，她不觉得过分吗？
  - 她叨钻难缠：我就阵重其事地问过她，在我自已的好的被一夜之间奇迹坏掉之后，我是否可以用她的二手热水壶？她不敢拒绝。
- 后来事情过去大家都平息点之后，她再说如果我看得上哪个二手的热水壶，她可以分出一半的费用。看她太可怜，是电器都会有坏的一天，也没人会看得上去买二手的，就拒绝了。说如果她的这个两人共用的又坏了，再商量对策。
- 她有果汁机，我也有自己的，我有收起自己的了吗？我不是每天用自己的，谁若不是自己的已经被用坏，谁真的看得上会愿意去用她的呢？
- 我的厨房电器，她什么都用，高压锅用得最多。

- 从今天起，保护自己的方式就是：不要再产生交集。
  - 早上早走，晚上尽量避开。必要时，不可避开时，能点个头说声 hi, 就当是问候过了。受不了她那种事儿经极端叨钻难缠的恶人。
  - 【绝不帮她】太耻辱了。帮助她，是天底下最大的自取其辱。她爱找谁帮忙，她找谁帮忙去。从此再不招惹她，太可恨，太可恶了！