#+latex_class: book
#+title: deepwaterooo deepwateroooMe -- I am the same GitHub account person
#+author: deepwaterooo

* me
- My *deepwaterooo* GitHub account ownership was taken away from me temporatorily,
  without reasonable update when they are supposed to return my
  ownership. 
- This *deepwateroooMe* GitHub account is the temporatorily newly
  created one to maintain my security, watching deepwaterooo account. 
- Once *deepwaterooo* ownership is returned back to me, I will switch
  back to deepwaterooo, and *leave this one linked with deepwaterooo account.*
- My *emacs configuration is still messy right now*. Because *they hide almost all the 5 repositories to be private* that I have even commited into GitHub
  ever since I worked for the company, leaving me no way to sync up my
  emacs configurations, nor any other about 3 repositories. 

* LOVE MY DEAR COUSIN: looking for PROFESSIONAL help form attorneys in related fields
Hi, 

I am facing *two different charges from Whitman
County Pullman WA*. 

The charges are: 
- 9A.36.041.2: ASSAULT 4TH DEGREE
- 9A.52.080: CRIMINAL TRESPASS-2ND DEGREE

I don't have any history with ASSAULT charges, and all the histories
of TRESPASS related were expired on 3/21/2017. 

I will be meeting the court judge soon within 2 - 3 weeks, and I am
looking for prefessional help to assist me though out the court dates and possibly
later trial. 

Please write to me *blue_water_000@hotmail.com*, if you are interested
and elligible for attorneys in *Whitman county, WA*, and please provide with your
quote as well. 

thanks. I look forward to hearing from you. 

* LUCID MOTORS
- They claimed that they have noticed that there are lucid data
  leaking for the past 2-3 weeks.
- They monitor my working laptop 365 -7 - 24, and they pretended that
  they just noticed such a matter. 
- Quite a few files in my GitHub account a few repositories clearly indicated it was me already.
- Leaking data into my personal cell phone was inspired and required
  by group leand Tianshi Li that I should take videos whenever I do
  car testing. He did provided a phone initially, but then he took the
  phone away, and how I supposed to record videos without a phone?
- They took my GitHub account deepwaterooo ownership away from me, and
  took everything DIGITAL away from me. 
- When they took my GitHub deepwaterooo account ownership away, they
  promised that they will return to me on Saturday, and latest by
  Monday 5pm. 
- Now it is Tuesday evening already, but they are taking forever to return my ownship. I NEED MY
 GitHub deepwaterooo OWNERSHIP BACK!
- Meanwhile the landloard wifi company is trying every means to block
  me from uploading anything into my newly opened deepwateroooMe
  GitHub account. I am NOT able to upload any larger repositories any
  more except simple files.  

* Looking for Android working oppotunities
- Hands on experience working on Android IPC (Interprocess communications, AIDL, Messenger, IBinder), and foreground/background services, starting local/binding remote services. Hands on experiences working on Broadcast Receiver, registered statically and dynamically.
- Hands on experiences on Java multithread programming; 
- Multiple project experiences with Handlers, AsyncTasks and IntentServices. 
- Project refactoring experience with MVVM, Singleton, Subscriber/Observer(Flow/Flowable) design patterns; 
- RxJava, ButterKnife frameworks, Jetpack Room, MVVM modules.
- Advanced user with Android Studio IDE building projects using either gradle (groovy or kotlin-programmed) or Android.mks. 
- Systematic exposure and practice on high level large project -- AOSP Android OS building pipeline and gradle configurations.
- Experience with automotive infotainment systems, from manipulating passing request signals through controllers to VHAL layer, and retrieving status signals from VHAL to upper Application layer SystemUI, CarSettings, System Settings, CarControls(Doors/Seats/Massages/Themes/Charging), HVAC Applications etc.
- Daily exposure and practice on AOSP various lower layer Car Services binding, remote ManagerServices. Well practiced on various controller/service binding / IPC listeners and callbacks registration and data passing.
- Projects refactoring experiences with Android 10 multiple user login/switching management, as well as user always login refactoring during suspend to ram and resume power management process/modules. 
- Experience building maps and navigation Apps.
- Familiarity with working with Linux / embedded systems.
- Experience working with Android framework, V-HAL, and building AOSP.
- Experience analyzing extremely large size Android log files, analysis ANRs, FATAL EXCEPTIONs and app CRASHES, memory leaks, and various delays.
- Widely detailed practices on various mac os/Linux commands, tools, widgets, configurations: iterm2/tmux, zsh, emacs, latex.....

* Hi Brian, 

Thanks for your udapte yesterday, and I have been waiting for your
update today, but it hasn't reached me yet. 

Before they took my GitHub ownership away, they promised that they
will return it back to me within 24 hours, which was Saturday
evening. They did request more time and estimated to be Monday 5pm. 
There are only 4 hidden repositories, and 3 of them are straighforward
no lucid data. I am having difficulty to understand why it take them
so long, without meanfully progress update?

Is it possible that you guide the team to review th repostories, and
release reviewed ones to be PUBLIC so that I would have access to
clone and sync up my local configurations for emacs and android
practice repositories etc?

Would you be able to help with an estimate of how soom I am supposed
to receive from HR for clearance? Is there any way that I can contact
HR directly, would email be possible?

I could NOT imagine it takes so long, and how long it will still
take. I expect that you could help gradully release my 4 hidden
repositories so that I could have access to them at least some of
them. While you and your team are still trying hard working on the
leaking data, after HR clearance, should I be able to return back to
work, while you still holding my GitHub deepwaterooo ownership?

I know I may have too many questions, but please understand that I am
put under stressful situations right now as well without valid updates, so if you could,
please help with updates. 

thanks. I look forward to hearing from you. 

Jenny Huang 

- regarding GitHub, we continue to work through the repositories and require more time. We will provide you another update tomorrow.
- I do not have an update on any return-to-work timing other than to tell you we anticipate that you will remain on paid suspension at least through Wednesday. Until such time that you are cleared by HR, you will not be permitted to return to campus.  I will remind HR to contact you at this email address this week with further details.
- please note that we need to continue control of the GitHub account and will update you as soon as we have a better understanding of when we can return that to you.