#+latex_class: book
#+title: deepwaterooo deepwateroooMe -- I am the same GitHub account person
#+author: deepwaterooo

* me
- My *deepwaterooo* GitHub account ownership was taken away from me temporatorily,
  without reasonable update when they are supposed to return my
  ownership. 
- This *deepwateroooMe* GitHub account is the temporatorily newly
  created one to maintain my security, watching deepwaterooo account. 
- Once *deepwaterooo* ownership is returned back to me, I will switch
  back to deepwaterooo, and *leave this one linked with deepwaterooo account.*
- My *emacs configuration is still messy right now*. Because *they hide almost all the 5 repositories to be private* that I have even commited into GitHub
  ever since I worked for the company, leaving me no way to sync up my
  emacs configurations, nor any other about 3 repositories. 

- 写给网络普通大众：未来十天天气预报

原本我也同大家一样
是弱弱无知无能无法理解网络炒作来着
但不幸被盯上炒作炒红
于是作为过气网红过来人的经验
总结归纳如下
帮助广大人民大众认知反省反思如下

借由英国女王的离世炒作
接下来十天的天气雨报如下
包括过气网红的认知总结

请任何普通人相信
任可所谓的网红被 炒作成名成为一名大家所认知的网红之前
她如大家一样是放牛的儿郞蓝天白云下作白日梦来着
她们如大家一样会吃饭拉屎挖鼻孔
与普能人无异
但是被炒作成名
更多的是被别人用心的炒作团体盯上
作为一个普通没有社会资源的网红
她们的命运更多的是一种
被动地被炒作用成名的无奈
以及今天再次被动地被一再地沷脏水被埋名的无奈

其实成名前的我们如山花野草般烂漫自在
请大家相信，再次被动地被埋名之后
我们同样会如山花野草般天花烂漫而自在
这是我们疗阔般草原里长大的胸襟与向往天性如此

请大家知晓
我已经连续两三个月被mitbbs.com禁止正常登录了
可以想像
他们借由他们的炒作喉舌
早已是把我炒作得面目全非；
大概一两周前
我的github account deepwaterooo账户多年来运行良好
也在他们现在炒作的关键时期被他们非正常死亡了
请大家知晓
当一个无名小辈被盯上而炒作成所谓的网红
她们的命名便被打上了无奈的标签
因为没有社会资源/无法挣脱他们的束缚
即便这些网红如我般
也有当年中考的全镇第一名
全县重点高中的第八名
即便这些网红先前有着鹤立鸡群般的聪明伶俐
被他们黑势力大势力施压下
无论她们的天资聪颖如何
都会被被动上扁压成无知无能
这也是被盯上被炒作成为所谓的网红的小人物的无奈

如果生活有选择
即便被他们炒作或是打压或是故意沷脏水之后
请大家仍然相信
被埋名后的她们仍然会选择如山花般烂漫地自由自在地生活
当他们为他们自己的利益与炒作方向导向
一再灵魂发问：
当年的XX妹妹，一定要嫁给穷小子，现在过得怎样了?
请大家本能在相信
当年的网红妹妹，为了她自己向往的爱情
即便是嫁给了穷小子
依然会有情饮水饱每天过得开开心心
生活得好得不能再好！

被他们炒作到如今这年头
不自已提供代住宅地址
不自己提供联系方式
供网上广大的社会大众随时方便就近跟踪
都不足以自证清白：
本人2006年全靠自己的努力
考上公费研究生申请奖学金出国留学
16年来定居美国
现居住加洲湾区东湾Union city 
Deborah 大街32476号，编号94587
电话号码：669-2121755
欢迎大家随时人肉，
条件方便的就近跟踪
不是任何时候
他们想要炒作成怎样
事实就是怎样的

今天最爱亲爱的表哥
一定要嫁给亲爱的表哥
爱表哥，爱生活~~！！！

* 写给偶们亲爱的表哥的情书
亲爱的表哥
这次回来
我终于找到了可是使用学校里帮助免费提供的无线网络
并且这次回来图书馆是开放的

不知道是不是前几天长途开车还没有缓过颈来
今天上午的脑袋还是昏昏的
还是说早上的咖啡里加得糖太多了犯昏呢？
于是乎，我再次坐进梦魅以求的图书馆里
做的事件是给亲爱的表哥写情书

每次回来
能够看见亲爱的表哥
我都总是狠开心
可是这次回来好几天了
我却还没能找到合适的机会看见亲爱的表哥

我知道舅舅和亲爱的表哥都是为我负责
所以才当年会早早地捶打911
无奈你的活宝妹早已是情根深种
心里面长了草种了草，心有所爱所庞
再来拔草
是舅舅和表哥用几十匹马、几十张火车皮来拉也拔不掉的

亲爱的表哥
10年底11年那时幼稚的自己
心心清清楚楚、明明白白地知道自己喜欢表哥
心里明白认定表哥
可是涉世不深，世俗里的障碍
让我固执地以为只要自己假装从来就不喜欢表哥
只要自己可以假装去爱上其它的人
只要自己能够按照世俗的标准
找个长相学历相配的人
便可以寐心地过完世俗标准下的一生

我以为我可以假装好一阵子
我以为我可以欺骗全世界
我以为我可以让所有的人都知道
我从来不曾爱过这样一位表哥
却原来我只假装得了一阵子
我以为我可以瞒天过海欺骗全世界
却原来我只是欺骗了我自己
浪费和虚度的从来都是自己的青春和光阴
我假装得了一时却假装不完一世

喜欢表哥
不是因为舅舅，不是因为任何感恩
情感中没有家庭轮理亲情关系上的感恩可言
更多也更应该是一个人内心情感的真正需求与向往
我喜欢表哥，不因为舅舅
喜欢表哥是因为，亲爱的表哥待我好
我曾被亲爱的表哥待我的好
真真切切、惊心动魂地感动过
感动到当时的自己就能清楚地认定
我遇见了对的人
这是我想要的幸福
我想要余生都被亲爱的表哥
温柔对待，时常宠爱，宠在心头掌心
亲爱的表哥，你看
你的这个妹妹从来都是把情感看得最重
把亲爱的表哥看得最重

曾经沧海难为水
除却巫山不是云
这两句话14个字成为我心口永远的痛
亲爱的表哥
我不止一次地问过你
你的心里是否留有别人的眼泪？
为什么你就一定接受不了你的这个活宝妹呢？
还是说，你只是简单地希望你的这个活宝妹
能够生活在大城市，能够物质上生活得相对好一点儿？

可是你的活宝妹从来都不是靠物质来活着的人呀
97年当我第一次遇见舅舅的时候
2007年当我来到美国后再次找到舅舅的时候
真正能够捆绑和牵挂住人的从来都是情
是幼稚少女时代心有郁结时候的鼓励解脱
是心里有所向往便想要努力踏入这片向往的国度土地的愿望
你的妹妹从来不是靠物质活着的人
你的妹妹更多的是听从她自己内心的声音活着
可是亲爱的表哥
那场告别、那场遇见
亲爱的表哥与我能够走到一起，但是佳缘是天作之合
可是亲爱的表哥如果一再拒绝我，那你的妹妹我便成了在劫难逃
你的妹妹今生也无法逃过这场爱情的劫难
表哥，你一再拒绝，要你这个妹妹后半生怎么过？
终究还是只能导致这个妹妹后半生残破残缺不全的人生

我能够想到的两种原因，我个人更愿意去相信前者
人的情感难以理解却也最为强求不得
我无法强求亲爱的表哥寐心地娶我
但借由我自己的经历换位思考
希望亲爱的表哥即便如我所猜测般心有所属又求而不得
希望已经回到故乡、能够生活在亲人环绕中的表哥
在父母兄弟亲人的陪伴中能够渐渐放宽自己的标准
希望亲爱的表哥能够遇见自己喜欢的女孩子
或是亲爱的表哥能够与生活妥协、学会接纳你的活宝妹

问世间情为何物
只叫人生死相许
我的后半生最想要同亲爱的表哥生活在一起
可是生活的风浪不知道会将我（们）打向何方
即便亲爱的表哥一时半会儿近年月或是近一两年还不能接纳我
我也希望在不久的将来
亲爱的表哥能够遇见自己的幸福或是能够接纳我
任何时候，能够看见亲爱的表哥生活得幸福
都是我这辈子最快乐的事
虽然我自己想要的幸福，是与亲爱的表哥在一起

亲爱的表哥
这次走后，我还会经常回来
访寻亲爱的表哥、我们的足迹曾经遍历过的地方
哪天亲爱的表哥改变主意了
肯求亲爱的表哥一定第一时间告诉我
这辈子能够嫁给亲爱的表哥
对我来说，任何时候都不晚

自己寻找来到美国
能够遇见亲爱的表哥
对我来说，即便是情感里的在劫难逃
却也是生命的礼遇，我狠感激
要不然，生活就是一串口枯井，了无生趣
等我老了，若是还没能嫁给表哥
我就回来亲爱的表哥所在这个城镇
在亲爱的表哥家的对面或是不远处
买个小房子
每天能够看见亲爱的表哥从我的窗前经过
都会成为我每天最大的点缀与快乐
谢谢亲爱的表哥！今生能够遇见亲爱的表哥
是我最幸福快乐和感激的事
且行且珍惜
愿我们很快能够执子之手，携手到老！

* LOVE MY DEAR COUSIN: looking for PROFESSIONAL help form attorneys in related fields
Hi, 

I am facing *two different charges from Whitman
County Pullman WA*. 

The charges are: 
- 9A.36.041.2: ASSAULT 4TH DEGREE
- 9A.52.080: CRIMINAL TRESPASS-2ND DEGREE

I don't have any history with ASSAULT charges, and all the histories
of TRESPASS related were expired on 3/21/2017. 

I will be meeting the court judge soon within 2 - 3 weeks, and I am
looking for prefessional help to assist me though out the court dates and possibly
later trial. 

Please write to me *blue_water_000@hotmail.com*, if you are interested
and elligible for attorneys in *Whitman county, WA*, and please provide with your
quote as well. 

thanks. I look forward to hearing from you. 

* LUCID MOTORS
- They claimed that they have noticed that there are lucid data
  leaking for the past 2-3 weeks.
- They monitor my working laptop 365 -7 - 24, and they pretended that
  they just noticed such a matter. 
- Quite a few files in my GitHub account a few repositories clearly indicated it was me already.
- Leaking data into my personal cell phone was inspired and required
  by group leand Tianshi Li that I should take videos whenever I do
  car testing. He did provided a phone initially, but then he took the
  phone away, and how I supposed to record videos without a phone?
- They took my GitHub account deepwaterooo ownership away from me, and
  took everything DIGITAL away from me. 
- When they took my GitHub deepwaterooo account ownership away, they
  promised that they will return to me on Saturday, and latest by
  Monday 5pm. 
- Now it is Tuesday evening already, but they are taking forever to return my ownship. I NEED MY
 GitHub deepwaterooo OWNERSHIP BACK!
- Meanwhile the landloard wifi company is trying every means to block
  me from uploading anything into my newly opened deepwateroooMe
  GitHub account. I am NOT able to upload any larger repositories any
  more except simple files.  

* Looking for Android working oppotunities
- Hands on experience working on Android IPC (Interprocess communications, AIDL, Messenger, IBinder), and foreground/background services, starting local/binding remote services. Hands on experiences working on Broadcast Receiver, registered statically and dynamically.
- Hands on experiences on Java multithread programming; 
- Multiple project experiences with Handlers, AsyncTasks and IntentServices. 
- Project refactoring experience with MVVM, Singleton, Subscriber/Observer(Flow/Flowable) design patterns; 
- RxJava, ButterKnife frameworks, Jetpack Room, MVVM modules.
- Advanced user with Android Studio IDE building projects using either gradle (groovy or kotlin-programmed) or Android.mks. 
- Systematic exposure and practice on high level large project -- AOSP Android OS building pipeline and gradle configurations.
- Experience with automotive infotainment systems, from manipulating passing request signals through controllers to VHAL layer, and retrieving status signals from VHAL to upper Application layer SystemUI, CarSettings, System Settings, CarControls(Doors/Seats/Massages/Themes/Charging), HVAC Applications etc.
- Daily exposure and practice on AOSP various lower layer Car Services binding, remote ManagerServices. Well practiced on various controller/service binding / IPC listeners and callbacks registration and data passing.
- Projects refactoring experiences with Android 10 multiple user login/switching management, as well as user always login refactoring during suspend to ram and resume power management process/modules. 
- Experience building maps and navigation Apps.
- Familiarity with working with Linux / embedded systems.
- Experience working with Android framework, V-HAL, and building AOSP.
- Experience analyzing extremely large size Android log files, analysis ANRs, FATAL EXCEPTIONs and app CRASHES, memory leaks, and various delays.
- Widely detailed practices on various mac os/Linux commands, tools, widgets, configurations: iterm2/tmux, zsh, emacs, latex.....

* Hi Brian, 

Thanks for your udapte yesterday, and I have been waiting for your
update today, but it hasn't reached me yet. 

Before they took my GitHub ownership away, they promised that they
will return it back to me within 24 hours, which was Saturday
evening. They did request more time and estimated to be Monday 5pm. 
There are only 4 hidden repositories, and 3 of them are straighforward
no lucid data. I am having difficulty to understand why it take them
so long, without meanfully progress update?

Is it possible that you guide the team to review th repostories, and
release reviewed ones to be PUBLIC so that I would have access to
clone and sync up my local configurations for emacs and android
practice repositories etc?

Would you be able to help with an estimate of how soom I am supposed
to receive from HR for clearance? Is there any way that I can contact
HR directly, would email be possible?

I could NOT imagine it takes so long, and how long it will still
take. I expect that you could help gradully release my 4 hidden
repositories so that I could have access to them at least some of
them. While you and your team are still trying hard working on the
leaking data, after HR clearance, should I be able to return back to
work, while you still holding my GitHub deepwaterooo ownership?

I know I may have too many questions, but please understand that I am
put under stressful situations right now as well without valid updates, so if you could,
please help with updates. 

thanks. I look forward to hearing from you. 

Jenny Huang 

- regarding GitHub, we continue to work through the repositories and require more time. We will provide you another update tomorrow.
- I do not have an update on any return-to-work timing other than to tell you we anticipate that you will remain on paid suspension at least through Wednesday. Until such time that you are cleared by HR, you will not be permitted to return to campus.  I will remind HR to contact you at this email address this week with further details.
- please note that we need to continue control of the GitHub account and will update you as soon as we have a better understanding of when we can return that to you.